version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: registro
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - "3307:3306"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app_container
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=registro
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge